name: Waste Model Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install ultralytics roboflow opencv-python matplotlib

      - name: Train YOLOv8 Model
        run: |
          yolo detect train data=datasets/waste-detection-1/data.yaml model=yolov8n.pt epochs=10 imgsz=640

#"GitHub Actions workflow for training"
